#!/usr/bin/env bash

$DEVSTRAP_TMP=/tmp
$DEVSTRAP_PATH="${DEVSTRAP_TMP}/devstrap"

if ! command -v git &> /dev/null; then sudo apt install -y git > /dev/null; fi

git clone -b stable https://github.com/etrepat/devstrap.git $DEVSTRAP_PATH > /dev/null

source $DEVSTRAP_PATH/devstrap.sh
