# Filesystem
alias ls="eza -lh --group-directories-first --icons auto"
alias lt="eza --tree --level=2 --long --icons auto --git"
alias ff="fzf --preview 'bat --style=numbers --color=always {}'"
alias df="df -h"
alias du="du -h --max-depth=1"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

# Utilities
#alias bat="batcat"
alias lzg="lazygit"
alias lzd="lazydocker"
alias icat="chafa"
alias zed="zeditor"
# vim is the system default ($EDITOR); if Neovim is installed you can uncomment
# this to use it from the terminal for convenience.
# alias vim="nvim"
alias rgf="rg --files | fzf --preview 'bat --style=numbers --color=always {}'"

# Git
alias g="git"
alias gcm="git commit -m"
alias gcam="git commit -a -m"
alias gcad="git commit -a --amend"
alias git-deploy="git push origin master && git push deploy master"
