# see https://github.com/eza-community/eza-themes/blob/main/themes/catppuccin-mocha.yml

colourful: true

filekinds:
  normal: { foreground: "#cdd6f4" }
  directory: { foreground: "#89b4fa" }
  symlink: { foreground: "#89dceb" }
  pipe: { foreground: "#45475a" }
  block_device: { foreground: "#f9e2af" }
  char_device: { foreground: "#f9e2af" }
  socket: { foreground: "#45475a" }
  special: { foreground: "#cba6f7" }
  executable: { foreground: "#a6e3a1" }
  mount_point: { foreground: "#94e2d5" }

perms:
  user_read: { foreground: "#89dceb" }
  user_write: { foreground: "#f9e2af" }
  user_execute_file: { foreground: "#a6e3a1" }
  user_execute_other: { foreground: "#a6e3a1" }
  group_read: { foreground: "#89dceb" }
  group_write: { foreground: "#fab387" }
  group_execute: { foreground: "#a6e3a1" }
  other_read: { foreground: "#89dceb" }
  other_write: { foreground: "#f38ba8" }
  other_execute: { foreground: "#a6e3a1" }
  special_user_file: { foreground: "#f38ba8" }
  special_other: { foreground: "#f38ba8" }
  attribute: { foreground: "#6c7086" }

size:
  major: { foreground: "#89dceb" }
  minor: { foreground: "#cba6f7" }
  number_byte: { foreground: "#a6adc8" }
  number_kilo: { foreground: "#74c7ec" }
  number_mega: { foreground: "#89dceb" }
  number_giga: { foreground: "#fab387" }
  number_huge: { foreground: "#f38ba8" }
  unit_byte: { foreground: "#a6adc8" }
  unit_kilo: { foreground: "#74c7ec" }
  unit_mega: { foreground: "#89dceb" }
  unit_giga: { foreground: "#fab387" }
  unit_huge: { foreground: "#f38ba8" }

users:
  user_you: { foreground: "#89b4fa" }
  user_root: { foreground: "#cba6f7" }
  user_other: { foreground: "#89dceb" }
  group_yours: { foreground: "#74c7ec" }
  group_root: { foreground: "#cba6f7" }
  group_other: { foreground: "#cdd6f4" }

links:
  normal: { foreground: "#74c7ec" }
  multi_link_file: { foreground: "#89dceb" }

git:
  new: { foreground: "#a6e3a1" }
  modified: { foreground: "#f9e2af" }
  deleted: { foreground: "#f38ba8" }
  renamed: { foreground: "#89b4fa" }
  typechange: { foreground: "#89dceb" }
  ignored: { foreground: "#45475a" }
  conflicted: { foreground: "#fab387" }

git_repo:
  branch_main: { foreground: "#6c7086" }
  branch_other: { foreground: "#94e2d5" }
  git_clean: { foreground: "#313244" }
  git_dirty: { foreground: "#f9e2af" }

security_context:
  colon: { foreground: "#45475a" }
  user: { foreground: "#6c7086" }
  role: { foreground: "#89dceb" }
  typ: { foreground: "#89b4fa" }
  range: { foreground: "#cba6f7" }

file_type:
  image: { foreground: "#74c7ec" }
  video: { foreground: "#94e2d5" }
  music: { foreground: "#a6e3a1" }
  lossless: { foreground: "#a6e3a1" }
  crypto: { foreground: "#f38ba8" }
  document: { foreground: "#a6adc8" }
  compressed: { foreground: "#fab387" }
  temp: { foreground: "#6c7086" }
  compiled: { foreground: "#6c7086" }
  build: { foreground: "#a6e3a1" }
  source: { foreground: "#cba6f7" }

punctuation: { foreground: "#45475a" }
date: { foreground: "#f9e2af" }
inode: { foreground: "#6c7086" }
blocks: { foreground: "#6c7086" }
header: { foreground: "#a6adc8" }
octal: { foreground: "#fab387" }
flags: { foreground: "#cba6f7" }

symlink_path: { foreground: "#74c7ec" }
control_char: { foreground: "#fab387" }
broken_symlink: { foreground: "#f38ba8" }
broken_path_overlay: { foreground: "#f38ba8" }